/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CardItem: typeof import('./src/components/home/CardItem.vue')['default']
    Carousel: typeof import('./src/components/commons/Carousel.vue')['default']
    Contact: typeof import('./src/components/home/Contact.vue')['default']
    copy: typeof import('./src/components/home/Posts copy.vue')['default']
    DanhGia: typeof import('./src/components/home/DanhGia.vue')['default']
    Error: typeof import('./src/components/commons/Error.vue')['default']
    Evaluate: typeof import('./src/components/home/Evaluate.vue')['default']
    Footer: typeof import('./src/components/commons/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HearderInfo: typeof import('./src/components/commons/HearderInfo.vue')['default']
    Info: typeof import('./src/components/home/Info.vue')['default']
    Intro: typeof import('./src/components/home/Intro.vue')['default']
    ListNew: typeof import('./src/components/home/ListNew.vue')['default']
    ListPhoto: typeof import('./src/components/home/ListPhoto.vue')['default']
    Loading: typeof import('./src/components/commons/Loading.vue')['default']
    Map: typeof import('./src/components/home/Map.vue')['default']
    Phone: typeof import('./src/components/home/Phone.vue')['default']
    Posts: typeof import('./src/components/home/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/home/Service.vue')['default']
    Test: typeof import('./src/components/home/Test.vue')['default']
  }
}
